-- 多变查询，用单个SELECT语句从读个表中查询相关的数据

-- 多表关联 如果没有加入条件 会产生笛卡尔积
SELECT emp.empno, emp.ename, emp.deptno, dept.deptno, dept.dname, dept.loc
FROM emp, dept;

SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;


-- 多表查询分为不同标准

-- 三表关联查询
SELECT E.*, D.*, L.*
FROM EMP E, DEPT D, LOCATIONS L
WHERE E.DEPTNO = D.DEPTNO AND D.LOC_ID = L.LOCID;





-- 本SQL中的 辅助语句
CREATE TABLE LOCATIONS(
   LOCID number(4) not null,
   LOCNAME varchar2(20)
);
ALTER TABLE LOCATIONS
   ADD CONSTRAINT PK_LOC PRIMARY KEY (LOCID);

INSERT INTO LOCATIONS VALUES(1000, '北京');
INSERT INTO LOCATIONS VALUES(1001, '上海');
INSERT INTO LOCATIONS VALUES(1002, '广州');
COMMIT;

-- 修改 DEPT 表中的地址，让它也变成一个外键约束
ALTER TABLE DEPT DROP COLUMN LOC;
ALTER TABLE DEPT ADD LOC_ID NUMBER(4);
ALTER TABLE DEPT 
   ADD CONSTRAINT FK_DEPT FOREIGN KEY (LOC_ID) REFERENCES LOCATIONS;


SELECT * FROM DEPT;


UPDATE EMP SET DEPTNO=null WHERE EMPNO = 7934;
COMMIT;

SELECT * FROM EMP;
SELECT * FROM DEPT;
